### **KEYBERT KEYWORD EXTRACTOR**

In [1]:
%pip install keybert

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.0/86.0 KB 2.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 238.7/238.7 KB 8.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.5/84.5 KB 5.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 20.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.8/6.8 MB 58.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 26.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.8/199.8 KB 16.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 22.1 MB/s eta 0:00:00
  Created wheel for keybert: filename=keybert-0.7.0-py3-none-any.whl size=23794 sha256=2d776c6600f5b12cc7cdb2c3bde1bd5da394751e47dd184d366a4a115af29ea7
  Stored in directory: /root/

In [2]:
from keybert import KeyBERT

In [3]:
kw_model = KeyBERT(model='all-mpnet-base-v2')

In [ ]:
keywords_nametext = kw_model.extract_keywords(name_text, stop_words='english', highlight=False,top_n=10,keyphrase_ngram_range=(2, 3),use_mmr=True,diversity=0.7)
# The diversity of the results between 0 and 1 if use_mmr is set to True.(diversity means different between words)
# use_mmr is for Whether to use Maximal Marginal Relevance (MMR) for the selection of keywords/keyphrases.(Maximum Marginal Relevance (MMR) is a ranking algorithm that has been widely used for subset selection.)

In [ ]:
keywords_list_name= list(dict(keywords_nametext).keys())

In [ ]:
print(keywords_list_name)

In [ ]:
subject_text = "Introduction to Digital communications and Spread Spectrum, Direct Sequence Spread Spectrum, Frequency Hopping, Pseudo-random sequence generation, Synchronization Issues for Spread-Spectrum, Performance analysis of Direct-Sequence Spread Spectrum, Frequency-Hopped Spread-Spectrum, and CDMA."

In [ ]:
keywords_subjecttext = kw_model.extract_keywords(subject_text, stop_words='english', highlight=False,top_n=10,keyphrase_ngram_range=(2, 3),diversity=0.7)

In [ ]:
keywords_list_subject= list(dict(keywords_subjecttext).keys())

In [ ]:
print(keywords_list_subject)

['spread spectrum cdma', 'communications spread spectrum', 'introduction digital communications', 'sequence spread spectrum', 'spread spectrum performance', 'digital communications spread', 'spread spectrum frequency', 'spectrum cdma', 'spectrum frequency hopping', 'frequency hopping']


## Get distinct word from sentences

In [ ]:
text = "'['spread spectrum cdma', 'communications spread spectrum', 'introduction digital communications', 'sequence spread spectrum', 'spread spectrum performance', 'digital communications spread', 'spread spectrum frequency', 'spectrum cdma', 'spectrum frequency hopping', 'frequency hopping']"

In [ ]:
words = text.replace("'", '')
words = words.split()
words = [word.strip('.,!;()[]') for word in words]
words = [word.replace("'s", '') for word in words]

#finding unique
unique = []
for word in words:
    if word not in unique:
        unique.append(word)

In [ ]:
print(unique)

['spread', 'spectrum', 'cdma', 'communications', 'introduction', 'digital', 'sequence', 'performance', 'frequency', 'hopping']


## Load Excel File

In [4]:
#import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
from google.colab import drive

In [6]:
drive.mount('/content/drive')

Mounted at /content/drive


In [7]:
courses_dataset = pd.read_excel('/content/drive/MyDrive//Colab Notebooks/Elective Courses.xlsx')

In [8]:
courses_dataset

Course Code                              Course Name  Semester  \
0     01CT0507                  Advanced Microprocessor         5   
1     01CT0508                    Optical Communication         5   
2     01CT0509                     Linux Administration         5   
3     01CT0510                   Applied Linear algebra         5   
4     01CT0511                    Theory of Computation         5   
5     01CT0604                   Embedded System Design         6   
6     01CT0605           RF and Microwave Communication         6   
7     01CT0606               Advanced Computer Networks         6   
8     01CT0607                         Machine learning         6   
9     01CT0608                          Compiler Design         6   
10    01CT0609                             VLSI Designs         6   
11    01CT0610                  Satellite Communication         6   
12    01CT0611                          Cloud Computing         6   
13    01CT0612         Data Warehousing and Data mining         6   
14    01CT0613                          .NET Technology         6   
15    01CT0705             Digital Design using Verilog         7   
16    01CT0706                          Computer Vision         7   
17    01CT0707                     Multimedia computing         7   
18    01CT0708                       Big Data Analytics         7   
19    01CT0709                             Advance Java         7   
20    01CT0710                Embedded Operating System         7   
21    01CT0711                   Wireless system Design         7   
22    01CT0712                       Internet of Things         7   
23    01CT0713  Programming for Application Development         7   
24    01CT0714               Human computer interaction         7   
25    01CT0802        Cross Platform Mobile Development         8   
26    01CT0803                SEO And Digital Marketing         8   
27    01CT0804                     VLSI Physical Design         8   
28    01CT0805                       Data Visualization         8   
29    01CT0806                         Advance Database         8   
30    01CT0807                   Network Administration         8   
31    01CT0808                 FPGA Based System Design         8   
32    01CT0809                  Advance C++ Programming         8   
33    01CT0810                         Game Development         8   
34    01CT0811             Introduction to Devops Tools         8   
35    01CT0812        Deep Learning for Computer Vision         8   
36    01CT0813                           Embedded Linux         8   
37    01CT0814           Spread Spectrum Communications         8   
38    01CT0815                   Advance Web Technology         8   

                                          Description  \
0   This course introduces the ARMv7 and ARMv7 Cor...   
1   To introduce the students to various optical f...   
2   To impart knowledge and skills on various prac...   
3   To learn important concepts of application of ...   
4   To understand thinking method of computer and ...   
5   This course introduces the basic concepts of E...   
6   This course is designed to understand and anal...   
7   Introduction of primary networking concepts an...   
8   Machine Intelligence concern with designing an...   
9   The purposive of this course is intended to te...   
10  The objective of this course is to introduce s...   
11  The goal of the course is to introduce student...   
12  This course is intended to analyse the basics ...   
13  The objective of this course is to introduce t...   
14  .Net Technologies are blend of technologies su...   
15  This course will introduce the students to the...   
16  Computer vision focuses on the development of ...   
17  Multimedia has become an essential part of mod...   
18  Big data is an extremely useful area in the er...   
19  This course develops programming ability of st...   
20  To acquire knowledge and skills about con

In [ ]:
courses_dataset['Unique Words']

## lexical analysis with finding similarity between unique words and input words

In [11]:
courses_dataset['Unique Words'][0].replace("'", "").replace("[","").replace("]","").replace(",","")

'tiva microcontroller course based armv7 cortexm architecture programming peripherals applications'

In [12]:
len(courses_dataset['Unique Words'])

39

In [ ]:
for i in range(0,len(courses_dataset['Unique Words'])):
  courses_dataset['Unique Words'][i] = courses_dataset['Unique Words'][i].replace("'", "").replace("[","").replace("]","").replace(",","")

In [ ]:
list(courses_dataset['Unique Words'])

In [ ]:
courses_dataset

Convert all list to mapped sentence

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [25]:
tfidf = TfidfVectorizer()

In [26]:
# get tf-df values
result = tfidf.fit_transform(courses_dataset['Unique Words'])

In [ ]:
for ele1, ele2 in zip(tfidf.get_feature_names_out(), tfidf.idf_):
    print(ele1, ':', ele2)

In [30]:
# get indexing
print('\nWord indexes:')
print(tfidf.vocabulary_)


Word indexes:
{'tiva': 269, 'microcontroller': 165, 'course': 67, 'based': 30, 'armv7': 25, 'cortexm': 66, 'architecture': 22, 'programming': 212, 'peripherals': 192, 'applications': 17, 'optical': 185, 'fiber': 100, 'study': 252, 'optic': 184, 'measurement': 161, 'techniques': 258, 'various': 284, 'associated': 27, 'amplifiers': 10, 'modes': 173, 'basics': 31, 'linux': 151, 'os': 186, 'theoretical': 264, 'aspects': 26, 'operating': 183, 'implementation': 129, 'using': 282, 'concepts': 55, 'application': 16, 'algebra': 7, 'mathematical': 160, 'modelling': 172, 'computation': 51, 'practical': 201, 'problems': 207, 'methods': 164, 'problem': 206, 'solving': 245, 'important': 130, 'numerical': 181, 'language': 143, 'processing': 209, 'method': 163, 'automata': 28, 'model': 171, 'finite': 102, 'computer': 52, 'thinking': 266, 'design': 79, 'provides': 215, 'computes': 53, 'systems': 257, 'rtos': 228, 'embedded': 90, 'introduce': 136, 'freertos': 111, 'real': 220, 'time': 267, 'lines': 149

In [ ]:
# display tf-idf values
print('\ntf-idf value:')
print(result)

In [32]:
# in matrix form
print('\ntf-idf values in matrix form:')
print(result.toarray())


tf-idf values in matrix form:
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [37]:
len(result.toarray()[0])

299

In [38]:
len(result.toarray()[1])

299

# Take user inputs

In [92]:
user_input = input()

my name is harsh jolapara and i am interested in flutter


In [94]:
#for user input
keywords_user_input = kw_model.extract_keywords(user_input, stop_words='english', highlight=False,top_n=10,diversity=0.7)

In [95]:
keywords_list_user_input= list(dict(keywords_user_input).keys())
keywords_list_user_input = ' '.join([str(x) for x in keywords_list_user_input])
keywords_list_user_input

'flutter interested jolapara harsh'

In [97]:
list1 = courses_dataset['Unique Words'].to_list()
list1.append(keywords_list_user_input)
# list1[39]

In [98]:
user_vectored = tfidf.fit_transform(list1)

In [ ]:
for ele1, ele2 in zip(tfidf.get_feature_names_out(), tfidf.idf_):
    print(ele1, ':', ele2)

In [99]:
user_vectored.shape

(40, 302)

In [100]:
len(user_vectored.toarray()[38])

302

In [101]:
len(user_vectored.toarray()[0])

302

In [102]:
# import required libraries
import numpy as np
from numpy.linalg import norm

array_len = len(user_vectored.toarray())

cosine_similarities = []

# compute cosine similarity
for i in range(0,array_len):
  cosine = np.dot(user_vectored.toarray()[array_len-1],user_vectored.toarray()[i])/(norm(user_vectored.toarray()[array_len-1])*norm(user_vectored.toarray()[i]))
  # print("Cosine Similarity:", cosine)
  cosine_similarities.append(cosine)

In [ ]:
cosine_similarities

In [103]:
from itertools import islice
cosine_similarities = list(islice(cosine_similarities, len(cosine_similarities)-1))
# cosine_similarities

In [104]:
index = cosine_similarities.index(max(cosine_similarities))
index

25

In [105]:
print("You can select subject : ",courses_dataset['Course Name'][index],", from semester : ",courses_dataset['Semester'][index],"th")

You can select subject :  Cross Platform Mobile Development , from semester :  8 th
